name: Arduino-Library-CI

on:
  
  push:
    branches: [ master, develop, feature/ci ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  
  build:
    name: Build ⚙️🔧
    runs-on: ubuntu-latest
    steps:

      - name: 📥📄 Clone current Library Repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: 🔧🤖 Arduino CI Build
        uses: Arduino-CI/action@v0.1.6

  
  deploy:
    name: Deploy ⚙️🚀
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'push'        
    steps:
      
      - name: 📥📄 Clone current Library Repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0  
          persist-credentials: false
      
      - name: 🔍 Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: 💬 Display branch name
        run: echo 'The current branch name is ' ${{ steps.extract_branch.outputs.branch }}
      
      - name: 🔧📜 Doxigen Build
        uses: mattnotmitt/doxygen-action@v1
          
      - name: 📥🌐 Clone current gh-pages barnch of the Library Repository
        uses: actions/checkout@v3.5.3
        with:
          ref: 'gh-pages'
          path: './.gh-pages'
          clean: true
          fetch-depth: 0   
          persist-credentials: false

      - name: ⚙️🔀 Running a little script to move files
        run: |
          rm -rf ./.gh-pages/docs/${{ steps.extract_branch.outputs.branch }}
          mkdir -p ./.gh-pages/docs/${{ steps.extract_branch.outputs.branch }}
          cp -r ./.doxygen/* ./.gh-pages/docs/${{ steps.extract_branch.outputs.branch }}

      - name: 🚀📜 Deploy Documentation 
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./.gh-pages
          CLEAN: true
